name: GiantShop
main: nl.giantit.minecraft.GiantShop.GiantShop
version: 0.9.DEV
authors: [Giant]
commands:
    shop:
        description: Shopping goes through here!
        aliases: [s]
        usage: /shop [params]
    loc:
        description: This will enable you to make shop locations!
        aliases: [shoploc, l, sl]
        usage: /loc [params]
    gsw:
        description: This will enable you to make shop locations!
        aliases: [gswapi, gsapi, g, gs, gswa]
        usage: /gsw [params]
permissions:
    giantshop.*:
        description: Gives access to all GiantShop permissions
        children:
            giantshop.shop.buy: true
            giantshop.shop.sell: true
            giantshop.shop.gift: true
            giantshop.shop.list: true
            giantshop.shop.check: true
            giantshop.shop.search: true
            giantshop.shop.discount.list: true
            giantshop.admin.send: true
            giantshop.admin.add: true
            giantshop.admin.update: true
            giantshop.admin.remove: true
            giantshop.admin.discount.list: true
            giantshop.admin.discount.add: true
            giantshop.admin.discount.update: true
            giantshop.admin.discount.remove: true
            giantshop.location.override: true
            giantshop.location.access: true
            giantshop.location.create: true
            giantshop.location.remove: true
            giantshop.location.list: true
            giantshop.api.web.list: true
            giantshop.api.web.register: true
            giantshop.api.web.pickup.list: true
            giantshop.api.web.pickup.pickup: true
            giantshop.api.web.pickup.all: true
    giantshop.shop.*:
        description: Gives access to the GiantShop payout
        children:
            giantshop.shop.buy: true
            giantshop.shop.sell: true
            giantshop.shop.gift: true
            giantshop.shop.list: true
            giantshop.shop.check: true
            giantshop.shop.search: true
            giantshop.shop.discount.list: true
    giantshop.admin.*:
        description: Gives access to all GiantShop admin commands
        children:
            giantshop.admin.sendhelp: true
            giantshop.admin.add: true
            giantshop.admin.update: true
            giantshop.admin.remove: true
            giantshop.admin.discount.list: true
            giantshop.admin.discount.add: true
            giantshop.admin.discount.update: true
            giantshop.admin.discount.remove: true
    giantshop.location.*:
        description: Gives access to all GiantShopLocation commands
        children:
            giantshop.location.override: true
            giantshop.location.access: true
            giantshop.location.create: true
            giantshop.location.remove: true
            giantshop.location.list: true
    giantshop.api.*:
        description: Gives access to all GiantShop API commands
        children:
            giantshop.api.web.register: true
            giantshop.api.web.list: true
            giantshop.api.web.pickup.list: true
            giantshop.api.web.pickup.pickup: true
            giantshop.api.web.pickup.all: true
    giantshop.api.web.*:
        description: Gives access to all GiantShopWeb API commands
        children:
            giantshop.api.web.register: true
            giantshop.api.web.list: true
            giantshop.api.web.pickup.list: true
            giantshop.api.web.pickup.pickup: true
            giantshop.api.web.pickup.all: true
    giantshop.shop.buy:
        description: Gives access to the buying feature
        default: false
    giantshop.shop.sell:
        description: Gives access to the selling feature
        default: false
    giantshop.shop.gift:
        description: Gives access to the gifting feature
        default: false
    giantshop.shop.list:
        description: Gives access to the item list feature
        default: false
    giantshop.shop.check:
        description: Gives access to the item checking feature
        default: false
    giantshop.shop.search:
        description: Gives access to the item searching feature
        default: false
    giantshop.shop.discount.list:
        description: Gives access to the discount list
        default: false
    giantshop.admin.sendhelp:
        description: Enables admin to send GiantShop help to user
        default: false
    giantshop.admin.add:
        description: Enables admin to add items to GiantShop
        default: false
    giantshop.admin.update:
        description: Enables admin to update items in GiantShop
        default: false
    giantshop.admin.remove:
        description: Enables admin to remove items from GiantShop
        default: false
    giantshop.admin.discount.list:
        description:  Enables admin to list all known discounts
        default: false
    giantshop.admin.discount.add:
        description: Enables admin to add discounts
        default: false
    giantshop.admin.discount.update:
        description: Enables admin to update discounts
        default: false
    giantshop.admin.discount.remove:
        description: Enables admin to remove discounts
        default: false
    giantshop.location.override:
        description: Enables admin to override location
        default: false
    giantshop.location.access:
        description: Enables admin to use location plugin
        default: false
    giantshop.location.create:
        description: Enables admin to create shop
        default: false
    giantshop.location.remove:
        description: Enables admin to remove shop
        default: false
    giantshop.location.list:
        description: Enables admin to list available shops
        default: false
    giantshop.api.web.list:
        description: Allows users to list all trusted webapi apps
        default: true
    giantshop.api.web.register:
        description: Allows users to register to a trusted webapi app
        default: true
    giantshop.api.web.pickup.list:
        description: Allows users to use delivery list
        default: true
    giantshop.api.web.pickup.pickup:
        description: Allows users to pickup a delivery
        default: true
    giantshop.api.web.pickup.all:
        description: Allows users to pickup all deliveries
        default: false